language: python
python:
- 3.5
before_install:
- pip install pep8
install:
- pip install -r requirements.txt
script:
- find . -name \*.py -exec pep8 --ignore=E402 {} +
- mkdir ./static/UserFile/
- python test_easyeditor.py
