language: python
python:
- 3.5
install:
- pip install coveralls
- pip install -r requirements.txt
script:
- mkdir ./static/UserFile/
- coverage run --source=easyeditor test_easyeditor.py
after_success:
  coveralls