language: python
python:
- 3.5
deploy:
  provider: heroku
  api_key:
    secure: dMVBM6ghm/HhjTBEdmYq4FsQLx2xUPf6K2p9H+DMlAwur09n8C64pzTkJGUEUK7dm6L6fuOtvsLZJ6igI4nQUyYxQA2gyy0G5Yzmy4FcmD/ka4LB4Ry5QpP7Z11MDiZb7lQUL9ka/LPXf1JatIpn9xtRd9Ebz7Y/hLPPY1ZoRLBCr1uWIQIAuqdXMzRAsyKrUxVMrYAY1P33aHzlz6y9DQd9WcbHYOYjQRl92aeFCJsivLzpz7BO69FNaT2lsiKwNPgCERJf5C10wBZv0snnKYzcjVyyuvliJBTBsoNV3ErPLlG4ZXCsvmqkXXhdgwOKea0D5GpHXHoVgfG9OXmEnm8n18GtjC04nbkO+KDWOhUNmDh8JgknUxdnndPJaaNEiwUczqRr4CbmD/sTWaOO+4oNA7eQAEceEK+7FQq1OnfLw2VfkFgIjBrp44dQXu5XvNTl9Iii7HxPoUJp8kSFCLqJlRPSsD9NuX+SRc6xvhKd8og93G/xYgX2vsT9uekgXm04hQx/svKuZpPsSjXfasApvI4MZ6q7+ZgyEk+BdPSwt2fgDYSGtdHNyliwEM04y7T6di+ttRipHl1FeOwHAF0RquoZWFyYXHPUlSGXtl6jvn2Rjjnd7QgIu7UoFu9iPbwEqEbX25bEzu70wa67dDPS4my8VWjJenbQD/yEBtU=
  app: EasyEditor
  on:
    repo: maxtortime/EasyEditor
before_install:
- pip install pep8
install:
- pip install -r requirements.txt
script:
- find . -name \*.py -exec pep8 --ignore=E402 {} +
- mkdir ./static/UserFile/
- python test_easyeditor.py
