language: python
python:
- 3.5
deploy:
  provider: heroku
  api_key:
    secure: "gG11jrVnZ05HKGre8/edMPLlhvbfp9mEEXk6fus1UUZ9Nm7FTGeVKVeIPR8vTFtgUtIZVgDYHx7W10/6tlzSvdCj1/Ee8xdMbwexaSgHo+mIn+WM/ox74uQon7K+ES2tZtY0MW1iShPOXvAV5OojNvjNRoAMeoOaIEpivHEjczmeYo1QbF7gMFFdhnX31QRfTDtfn0QMqI5Ly5hevBl68W6kbsZZCEMe4wGxuEnglR0DgOQLA0rC92bFsptU97PoZuaYJnNCNhMpKKXSd0OKH6GA+rXw6t9hWzF/7v+4USrdC5MtjflQecBoVPsmPosXCY1LIT6rLXnn7cVb/CY6VB5QlAXUnWHiGIB0KUb73rZ7iwTlajMmWcID42EjVq3eyYprOYmT//NErjUHAI2Sl0+N53xXQalRkacup3/VLQQM72rt7Lex4nkOyN+mwAx6oXI/YXvha6+kHoMke9yOR+5/AQZmzri5iNyO3t7jYgGWJePPhGK0qg0jn5xMj0FrCnlu3DqJMbA2AEiVAueHiFPoJzckadMomKGUjL6rpjbBSaqB3sdqDbYCYvXebpyd4Dmy62UG0JsKEskhrmccaPHe4DRgPbadnuTmT15sr6Y56bNirfjVqIPowxw9blf2AYUFvIPRH1GxIScD4mhEYhf+7OmY4GgMyjkilJFl/ds="
  app: EasyEditor
  on:
    repo: maxtortime/EasyEditor
before_install:
- pip install pep8
install:
- pip install -r requirements.txt
script:
- find . -name \*.py -exec pep8 --ignore=E402 {} +
- mkdir ./static/UserFile/
- python test_easyeditor.py
